/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Eleicoes2026RouteImport } from './routes/eleicoes2026'
import { Route as LinktreeRouteImport } from './routes/linktree'
import { Route as MoldurasRouteImport } from './routes/molduras'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as StickerGalleryRouteImport } from './routes/sticker-gallery'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Eleicoes2026Route = Eleicoes2026RouteImport.update({
  id: '/eleicoes2026',
  path: '/eleicoes2026',
  getParentRoute: () => rootRouteImport,
} as any)
const LinktreeRoute = LinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => rootRouteImport,
} as any)
const MoldurasRoute = MoldurasRouteImport.update({
  id: '/molduras',
  path: '/molduras',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const StickerGalleryRoute = StickerGalleryRouteImport.update({
  id: '/sticker-gallery',
  path: '/sticker-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eleicoes2026': typeof Eleicoes2026Route
  '/linktree': typeof LinktreeRoute
  '/molduras': typeof MoldurasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sticker-gallery': typeof StickerGalleryRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eleicoes2026': typeof Eleicoes2026Route
  '/linktree': typeof LinktreeRoute
  '/molduras': typeof MoldurasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sticker-gallery': typeof StickerGalleryRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eleicoes2026': typeof Eleicoes2026Route
  '/linktree': typeof LinktreeRoute
  '/molduras': typeof MoldurasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sticker-gallery': typeof StickerGalleryRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eleicoes2026'
    | '/linktree'
    | '/molduras'
    | '/privacidade'
    | '/sticker-gallery'
    | '/termos-de-uso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eleicoes2026'
    | '/linktree'
    | '/molduras'
    | '/privacidade'
    | '/sticker-gallery'
    | '/termos-de-uso'
  id:
    | '__root__'
    | '/'
    | '/eleicoes2026'
    | '/linktree'
    | '/molduras'
    | '/privacidade'
    | '/sticker-gallery'
    | '/termos-de-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Eleicoes2026Route: typeof Eleicoes2026Route
  LinktreeRoute: typeof LinktreeRoute
  MoldurasRoute: typeof MoldurasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  StickerGalleryRoute: typeof StickerGalleryRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleicoes2026': {
      id: '/eleicoes2026'
      path: '/eleicoes2026'
      fullPath: '/eleicoes2026'
      preLoaderRoute: typeof Eleicoes2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linktree': {
      id: '/linktree'
      path: '/linktree'
      fullPath: '/linktree'
      preLoaderRoute: typeof LinktreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molduras': {
      id: '/molduras'
      path: '/molduras'
      fullPath: '/molduras'
      preLoaderRoute: typeof MoldurasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sticker-gallery': {
      id: '/sticker-gallery'
      path: '/sticker-gallery'
      fullPath: '/sticker-gallery'
      preLoaderRoute: typeof StickerGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Eleicoes2026Route: Eleicoes2026Route,
  LinktreeRoute: LinktreeRoute,
  MoldurasRoute: MoldurasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  StickerGalleryRoute: StickerGalleryRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
